version: '2'
services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web/public:/var/www/SyncMe_SERVER"
            - "uploaddata:/var/www/SyncMe_UPLOAD"
        depends_on:
            - "php"
            - "mongodb"
    php:
        image: dvlpm/php7.4-dev
        container_name: php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web/public:/var/www/SyncMe_SERVER
            - "uploaddata:/var/www/SyncMe_UPLOAD"
    composer:
        image: composer/composer
        container_name: composer
        volumes:
            - ./web/public:/var/www/SyncMe_SERVER
        working_dir: /var/www/SyncMe_SERVER
        command: install
    mongodb:
        image: mongo
        container_name: mongo
        container_name: mongo
        restart: always
        volumes:
            - "mongodbdata:/data/db"
        ports:
            - "27020:27017"
        command: mongod --logpath=/dev/null

volumes:
    mongodbdata:
        external: true
    uploaddata:
